from __future__ import annotations
import html,json,os,zipfile
from datetime import datetime,timezone
from html.parser import HTMLParser
from pathlib import Path
from zoneinfo import ZoneInfo
import requests
from playwright.sync_api import sync_playwright

ROOT=Path(__file__).resolve().parent
OUT=ROOT/'output'; IMG=OUT/'images'; MAN=OUT/'manifest.json'
NEWS=json.loads((ROOT/'news.json').read_text(encoding='utf-8'))
POOL=json.loads((ROOT/'curated_pool.json').read_text(encoding='utf-8'))
BING='https://www.bing.com/images/search'
TARGET=int(os.getenv('IMAGES_PER_NEWS','3'))
S=requests.Session();S.headers.update({'User-Agent':'Mozilla/5.0 Chrome/126 daily-news-image-pack/17.0','Accept-Language':'en-US,en;q=0.9'})
REJECT=('illustration','drawing','painting','poster','logo','icon','render','rendering','infographic','cartoon','collage','3d','vector','wallpaper','concept art','fan art','ai generated','generated by ai','midjourney','stable diffusion','dall-e','dalle','diagram','chart','graph','map')
STORY={1:(['hormuz','persian gulf','gulf of oman'],['ship','vessel','navy','tanker']),2:(['kyiv','kiev'],['damage','destroy','attack','strike','building','city']),3:(['iran','iranian'],['radar','air base','airbase','military','missile','facility','installation']),4:(['hormuz','persian gulf','gulf of oman'],['merchant','cargo','tanker','ship','vessel']),5:(['tanker','oil tanker','crude carrier'],['ship','vessel','gulf','hormuz','sea']),6:(['qatar','qatarenergy','qatargas','persian gulf'],['lng','liquefied natural gas','gas carrier','carrier']),7:(['black sea','bosphorus','ukraine','turkey'],['cargo','merchant','ship','vessel','freighter']),8:(['data center','datacenter','server'],['rack','server','data centre']),9:(['china','chinese','xinjiang','khorgos'],['freight','container','intermodal','rail','train','logistics']),10:(['china','shenzhen','xinjiang'],['transmission','power grid','substation','tower','high voltage','electricity']),11:(['china','hong kong','construction'],['worker','helmet','hard hat','safety','protective']),12:(['xinjiang','turpan','urumqi','china'],['solar','photovoltaic','energy storage','power station','wind farm','renewable']),13:(['khorgos','horgos','xinjiang'],['port','border','freight','truck','train','terminal','customs'])}
AVOID={1:['gibraltar','suez','panama'],2:['moscow','odesa','odessa','kharkiv'],3:['iraq','ain al-assad','museum'],4:['gibraltar','suez'],5:['motor oil','lubricant','engine oil','bottle'],6:['sunset','resort','beach','tourism'],7:['cruise','yacht'],8:['gaming'],9:['great wall','flag','tourist'],10:['telecom tower','cell tower'],11:['shopping','isolated helmet'],12:['foundation','trantor','sci-fi'],13:['wedding','battery','hotel','restaurant']}

class BP(HTMLParser):
 def __init__(self):super().__init__();self.items=[]
 def handle_starttag(self,tag,attrs):
  if tag!='a':return
  d=dict(attrs);m=d.get('m')
  if 'iusc' not in d.get('class','') or not m:return
  try:o=json.loads(html.unescape(m))
  except:return
  u=o.get('murl') or o.get('turl') or '';p=o.get('purl') or '';t=o.get('t') or o.get('desc') or ''
  if p:self.items.append({'image_url':u,'source_page':p,'title':t})

def txt(*x):return ' '.join((v or '') for v in x).lower()
def topic_ok(i,*parts):
 b=txt(*parts)
 if any(k in b for k in REJECT) or any(a in b for a in AVOID[i]):return False
 g1,g2=STORY[i]
 return any(a in b for a in g1) and any(a in b for a in g2)

def bing(q,i):
 try:
  rq=f'{q} 2026 2025 photo photograph -illustration -render -wallpaper -AI'
  r=S.get(BING,params={'q':rq,'qft':'+filterui:photo-photo','form':'HDRSC3'},timeout=25);r.raise_for_status();p=BP();p.feed(r.text)
 except:return []
 out=[];seen=set()
 for x in p.items:
  if not topic_ok(i,x['title'],x['source_page'],x['image_url']):continue
  if x['source_page'] in seen:continue
  seen.add(x['source_page']);out.append(x)
  if len(out)>=20:break
 return out

def screenshot_best_image(page,path:Path):
 best=None;best_area=0
 try:
  imgs=page.locator('img')
  for idx in range(min(imgs.count(),120)):
   el=imgs.nth(idx)
   try:
    box=el.bounding_box()
    if not box:continue
    w=float(box.get('width') or 0);h=float(box.get('height') or 0);area=w*h
    if w>=420 and h>=240 and area>best_area:
     best=el;best_area=area
   except:continue
  if best is not None:
   best.scroll_into_view_if_needed(timeout=3000);page.wait_for_timeout(300);best.screenshot(path=str(path));return 'largest_visible_image_element'
 except:pass
 page.screenshot(path=str(path),full_page=False);return 'viewport_fallback'

def main():
 data=json.loads(MAN.read_text(encoding='utf-8'));IMG.mkdir(parents=True,exist_ok=True)
 byid={int(x['id']):x for x in data.get('items',[])};shot_total=0
 with sync_playwright() as pw:
  browser=pw.chromium.launch(headless=True,args=['--disable-dev-shm-usage'])
  ctx=browser.new_context(viewport={'width':1440,'height':900},locale='en-US')
  for item in NEWS:
   i=int(item['id']);rec=byid.get(i)
   if not rec:continue
   rec.setdefault('screenshots',[])
   existing=len(rec.get('images',[]))+len(rec.get('screenshots',[]));need=max(0,TARGET-existing)
   if not need:continue
   qs=list((POOL.get(str(i),{}) or {}).get('queries') or [])
   if item.get('title'):qs.append(item['title'])
   candidates=[];seen=set()
   for q in qs:
    for c in bing(q,i):
     if c['source_page'] not in seen:seen.add(c['source_page']);candidates.append(c)
   for c in candidates:
    if len(rec['images'])+len(rec['screenshots'])>=TARGET:break
    page=ctx.new_page()
    try:
     page.goto(c['source_page'],wait_until='domcontentloaded',timeout=25000);page.wait_for_timeout(1600)
     title=(page.title() or c['title'] or '')[:300];body=(page.locator('body').inner_text(timeout=5000) or '')[:10000]
     if not topic_ok(i,title,body,c['source_page']):continue
     slot=len(rec['images'])+len(rec['screenshots'])+1;fn=f'{i:02d}_{slot}.png';path=IMG/fn
     mode=screenshot_best_image(page,path)
     rec['screenshots'].append({'file':fn,'asset_type':'webpage_screenshot','source_page':c['source_page'],'search_result_title':c['title'],'captured_at_utc':datetime.now(timezone.utc).isoformat(),'screenshot_mode':mode,'counts_toward_39':True,'usage_note':'User stated non-commercial use. Screenshot remains subject to the source material copyright/terms; non-commercial use does not itself remove copyright obligations.','access_controls_bypassed':False})
     shot_total+=1
    except Exception:pass
    finally:
     try:page.close()
     except:pass
  browser.close()

 visual_total=sum(len(x.get('images',[]))+len(x.get('screenshots',[])) for x in data.get('items',[]))
 data['version']='17.0-original-first-counted-screenshot-fallback';data['screenshot_count']=shot_total;data['visual_asset_count']=visual_total;data['missing_visual_assets']=13*TARGET-visual_total
 rules=data.setdefault('rules',{});rules['screenshots_count_toward_target']=True;rules['target_visual_assets']=13*TARGET;rules['original_photo_preferred']=True;rules['screenshot_fallback_when_original_unavailable']=True;rules['no_bypass_of_paywall_login_drm_or_access_controls']=True
 MAN.write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
 readme=OUT/'README_来源与许可.txt';old=readme.read_text(encoding='utf-8') if readme.exists() else ''
 readme.write_text(old+'\n\nV17：优先保存符合要求的近期实拍原图；原图无法取得时，用公开可访问来源页中的最大可见图片区域截图补足每条3个视觉素材。截图计入39个视觉素材目标，但manifest会明确标记为webpage_screenshot。截图不绕过付费墙、登录、DRM或其他访问控制；非商业使用也不等于自动获得版权许可。\n',encoding='utf-8')
 stamp=datetime.now(ZoneInfo('Asia/Shanghai')).strftime('%Y-%m-%d');zp=ROOT/f'daily-news-images-{stamp}.zip'
 if zp.exists():zp.unlink()
 with zipfile.ZipFile(zp,'w',zipfile.ZIP_DEFLATED) as z:
  for p in sorted(IMG.iterdir()):z.write(p,p.name)
  z.write(MAN,'manifest.json');z.write(readme,'README_来源与许可.txt')
 print(f'V17 screenshots added={shot_total}; visual assets={visual_total}/{13*TARGET}; ZIP={zp.name}')

if __name__=='__main__':main()
