from __future__ import annotations
import html,json,os,re,zipfile
from datetime import datetime,timezone
from html.parser import HTMLParser
from pathlib import Path
from zoneinfo import ZoneInfo
import requests
from playwright.sync_api import sync_playwright

ROOT=Path(__file__).resolve().parent
OUT=ROOT/'output'
REF=OUT/'reference_screenshots'
NEWS=json.loads((ROOT/'news.json').read_text(encoding='utf-8'))
POOL=json.loads((ROOT/'curated_pool.json').read_text(encoding='utf-8'))
MAN=OUT/'manifest.json'
BING='https://www.bing.com/images/search'
LIMIT=int(os.getenv('REFERENCE_SCREENSHOTS_PER_NEWS','3'))
S=requests.Session();S.headers.update({'User-Agent':'Mozilla/5.0 Chrome/126 daily-news-image-pack/16.0','Accept-Language':'en-US,en;q=0.9'})
REJECT=('illustration','drawing','painting','poster','logo','icon','render','rendering','infographic','cartoon','collage','3d','vector','wallpaper','concept art','fan art','ai generated','generated by ai','midjourney','stable diffusion','dall-e','dalle','diagram','chart','graph','map')
STORY={1:(['hormuz','persian gulf','gulf of oman'],['ship','vessel','navy','tanker']),2:(['kyiv','kiev'],['damage','destroy','attack','strike','building','city']),3:(['iran','iranian'],['radar','air base','airbase','military','missile','facility','installation']),4:(['hormuz','persian gulf','gulf of oman'],['merchant','cargo','tanker','ship','vessel']),5:(['tanker','oil tanker','crude carrier'],['ship','vessel','gulf','hormuz','sea']),6:(['qatar','qatarenergy','qatargas','persian gulf'],['lng','liquefied natural gas','gas carrier','carrier']),7:(['black sea','bosphorus','ukraine','turkey'],['cargo','merchant','ship','vessel','freighter']),8:(['data center','datacenter','server'],['rack','server','data centre']),9:(['china','chinese','xinjiang','khorgos'],['freight','container','intermodal','rail','train','logistics']),10:(['china','shenzhen','xinjiang'],['transmission','power grid','substation','tower','high voltage','electricity']),11:(['china','hong kong','construction'],['worker','helmet','hard hat','safety','protective']),12:(['xinjiang','turpan','urumqi','china'],['solar','photovoltaic','energy storage','power station','wind farm','renewable']),13:(['khorgos','horgos','xinjiang'],['port','border','freight','truck','train','terminal','customs'])}
AVOID={1:['gibraltar','suez','panama'],2:['moscow','odesa','odessa','kharkiv'],3:['iraq','ain al-assad','museum'],4:['gibraltar','suez'],5:['motor oil','lubricant','engine oil','bottle'],6:['sunset','resort','beach','tourism'],7:['cruise','yacht'],8:['gaming'],9:['great wall','flag','tourist'],10:['telecom tower','cell tower'],11:['shopping','isolated helmet'],12:['foundation','trantor','sci-fi'],13:['wedding','battery','hotel','restaurant']}

class BP(HTMLParser):
 def __init__(self):super().__init__();self.items=[]
 def handle_starttag(self,tag,attrs):
  if tag!='a':return
  d=dict(attrs);m=d.get('m')
  if 'iusc' not in d.get('class','') or not m:return
  try:o=json.loads(html.unescape(m))
  except:return
  u=o.get('murl') or o.get('turl');p=o.get('purl') or '';t=o.get('t') or o.get('desc') or ''
  if p:self.items.append({'image_url':u or '', 'source_page':p,'title':t})

def txt(*x):return ' '.join((v or '') for v in x).lower()
def topic_ok(i,*parts):
 b=txt(*parts)
 if any(k in b for k in REJECT) or any(a in b for a in AVOID[i]):return False
 g1,g2=STORY[i]
 return any(a in b for a in g1) and any(a in b for a in g2)

def bing(q,i):
 try:
  rq=f'{q} 2026 2025 photo photograph -illustration -render -wallpaper -AI'
  r=S.get(BING,params={'q':rq,'qft':'+filterui:photo-photo','form':'HDRSC3'},timeout=25);r.raise_for_status();p=BP();p.feed(r.text)
 except:return []
 out=[];seen=set()
 for x in p.items:
  if not topic_ok(i,x['title'],x['source_page'],x['image_url']):continue
  u=x['source_page']
  if u in seen:continue
  seen.add(u);out.append(x)
  if len(out)>=LIMIT*4:break
 return out

def main():
 data=json.loads(MAN.read_text(encoding='utf-8'))
 REF.mkdir(parents=True,exist_ok=True)
 byid={int(x['id']):x for x in data.get('items',[])}
 total=0
 with sync_playwright() as pw:
  browser=pw.chromium.launch(headless=True,args=['--disable-dev-shm-usage'])
  ctx=browser.new_context(viewport={'width':1440,'height':900},locale='en-US')
  for item in NEWS:
   i=int(item['id']);rec=byid.get(i)
   if not rec:continue
   need=max(0,LIMIT-len(rec.get('images',[])))
   rec['reference_screenshots']=[]
   if not need:continue
   qs=list((POOL.get(str(i),{}) or {}).get('queries') or [])
   if item.get('title'):qs.append(item['title'])
   candidates=[];seen=set()
   for q in qs:
    for c in bing(q,i):
     if c['source_page'] not in seen:
      seen.add(c['source_page']);candidates.append(c)
   for c in candidates:
    if len(rec['reference_screenshots'])>=need:break
    page=ctx.new_page()
    try:
     page.goto(c['source_page'],wait_until='domcontentloaded',timeout=25000)
     page.wait_for_timeout(1800)
     title=(page.title() or c['title'] or '')[:240]
     body=(page.locator('body').inner_text(timeout=5000) or '')[:8000]
     if not topic_ok(i,title,body,c['source_page']):
      page.close();continue
     fn=f'{i:02d}_ref_{len(rec["reference_screenshots"])+1}.png'
     path=REF/fn
     page.screenshot(path=str(path),full_page=False)
     rec['reference_screenshots'].append({'file':f'reference_screenshots/{fn}','source_page':c['source_page'],'search_result_title':c['title'],'captured_at_utc':datetime.now(timezone.utc).isoformat(),'usage_status':'REFERENCE_ONLY_不可直接发布','counts_toward_39':False,'purpose':'reference screenshot of source webpage; not a substitute for licensed/original image','copyright_note':'Screenshot does not remove copyright. Verify permission/license before publication.'})
     total+=1
    except Exception as e:
     pass
    finally:
     try:page.close()
     except:pass
  browser.close()
 data['version']='16.0-original-first-reference-screenshot-fallback'
 data['reference_screenshot_count']=total
 data.setdefault('rules',{})['reference_screenshot_fallback']=True
 data['rules']['reference_screenshots_count_toward_target']=False
 data['rules']['reference_screenshot_usage']='REFERENCE_ONLY_不可直接发布'
 data['rules']['screenshot_does_not_bypass_copyright_or_site_access_controls']=True
 MAN.write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
 readme=OUT/'README_来源与许可.txt'
 old=readme.read_text(encoding='utf-8') if readme.exists() else ''
 readme.write_text(old+'\n\nV16 参考截图兜底：当可直接使用的近期实拍原图不足时，可把高相关来源网页截屏放入 reference_screenshots/。这些文件仅作选图线索，不计入39张可发布图片，不得把截图理解为绕过版权、付费墙、防盗链或下载限制。发布前仍需核实图片授权。\n',encoding='utf-8')
 stamp=datetime.now(ZoneInfo('Asia/Shanghai')).strftime('%Y-%m-%d');zp=ROOT/f'daily-news-images-{stamp}.zip'
 with zipfile.ZipFile(zp,'a',zipfile.ZIP_DEFLATED) as z:
  for p in sorted(REF.glob('*.png')):z.write(p,f'reference_screenshots/{p.name}')
  z.writestr('manifest.json',MAN.read_text(encoding='utf-8'))
  z.writestr('README_来源与许可.txt',readme.read_text(encoding='utf-8'))
 print(f'V16 reference screenshots added: {total}; ZIP={zp.name}')

if __name__=='__main__':main()
