from __future__ import annotations
import json, os, zipfile
from datetime import datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo
from urllib.parse import quote_plus
from playwright.sync_api import sync_playwright

ROOT=Path(__file__).resolve().parent
OUT=ROOT/'output'
MAN=OUT/'manifest.json'
NEWS=json.loads((ROOT/'news.json').read_text(encoding='utf-8'))
POOL=json.loads((ROOT/'curated_pool.json').read_text(encoding='utf-8'))
TARGET=int(os.getenv('IMAGES_PER_NEWS','3'))
BING='https://www.bing.com/images/search?q='
REJECT=('illustration','drawing','painting','poster','logo','icon','render','rendering','infographic','cartoon','collage','3d','vector','wallpaper','concept art','fan art','ai generated','generated by ai','midjourney','stable diffusion','dall-e','dalle','diagram','chart','graph','map')
AVOID={1:['gibraltar','suez','panama'],2:['moscow','odesa','odessa','kharkiv'],3:['iraq','ain al-assad','museum'],4:['gibraltar','suez'],5:['motor oil','lubricant','engine oil','bottle','saint petersburg'],6:['sunset','resort','beach','tourism'],7:['cruise','yacht'],8:['gaming'],9:['great wall','flag','tourist'],10:['skyscraper','telecom tower','cell tower'],11:['shopping','isolated helmet'],12:['foundation','trantor','sci-fi'],13:['wedding','battery','hotel','restaurant']}
FALLBACK={
1:['Strait of Hormuz tanker ship 2026 photo','Gulf of Oman commercial ship 2026 photo','Hormuz naval vessel 2026 photo'],
2:['Kyiv building damage 2026 photo','Kyiv Russian attack damage 2026 photo','Kyiv damaged apartment 2026 photo'],
3:['Iran military radar facility 2026 photo','Iran air base 2026 photo','Iran missile facility 2026 photo'],
4:['Strait of Hormuz merchant ship 2026 photo','Hormuz cargo vessel 2026 photo','Persian Gulf tanker 2026 photo'],
5:['Persian Gulf oil tanker 2026 photo','Strait of Hormuz oil tanker 2026 photo','Gulf of Oman crude tanker 2026 photo'],
6:['QatarEnergy LNG carrier 2026 photo','Qatar LNG tanker 2026 photo','LNG carrier Persian Gulf 2026 photo'],
7:['Black Sea cargo ship 2026 photo','Bosphorus merchant ship 2026 photo','Ukraine Black Sea freighter 2026 photo'],
8:['China data center server racks 2026 photo','AI data center China 2026 photo','server room racks 2026 photo'],
9:['China container freight train 2026 photo','China intermodal freight terminal 2026 photo','China logistics rail terminal 2026 photo'],
10:['China power grid transmission tower 2026 photo','China substation 2026 photo','China high voltage grid 2026 photo'],
11:['China construction workers safety helmets 2026 photo','construction worker protective equipment China 2026 photo','Chinese workers hard hats 2026 photo'],
12:['Xinjiang solar farm 2026 photo','Turpan solar power station 2026 photo','Xinjiang energy storage 2026 photo'],
13:['Khorgos port trucks 2026 photo','Khorgos freight terminal 2026 photo','Khorgos border port train 2026 photo']}

def bad_text(s,i):
    b=(s or '').lower()
    return any(x in b for x in REJECT) or any(x in b for x in AVOID.get(i,[]))

def existing_count(rec):
    return len(rec.get('images') or [])+len(rec.get('screenshots') or [])

def next_filename(i,rec):
    return f'{i:02d}_{existing_count(rec)+1}.png'

def query_list(i):
    qs=[]
    for q in (POOL.get(str(i),{}) or {}).get('queries') or []:
        if q and q not in qs: qs.append(q)
    for q in FALLBACK.get(i,[]):
        if q not in qs: qs.append(q)
    return qs

def main():
    data=json.loads(MAN.read_text(encoding='utf-8'))
    byid={int(x['id']):x for x in data.get('items',[])}
    added=0
    with sync_playwright() as pw:
        browser=pw.chromium.launch(headless=True,args=['--disable-dev-shm-usage','--no-sandbox'])
        ctx=browser.new_context(viewport={'width':1600,'height':1200},locale='en-US',user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36')
        page=ctx.new_page()
        for item in NEWS:
            i=int(item['id']); rec=byid.get(i)
            if not rec: continue
            rec.setdefault('screenshots',[])
            seen=set()
            for q in query_list(i):
                if existing_count(rec)>=TARGET: break
                try:
                    page.goto(BING+quote_plus(q+' -illustration -render -wallpaper -AI'),wait_until='domcontentloaded',timeout=35000)
                    page.wait_for_timeout(2500)
                    # Try several Bing layouts. We screenshot only visible image-result elements.
                    candidates=[]
                    for sel in ['img.mimg','a.iusc img','div.mimg img','img[src*="bing.net/th"]','img']:
                        loc=page.locator(sel)
                        try: n=min(loc.count(),120)
                        except: n=0
                        for idx in range(n):
                            candidates.append(loc.nth(idx))
                    for img in candidates:
                        if existing_count(rec)>=TARGET: break
                        try:
                            box=img.bounding_box()
                            if not box or box['width']<140 or box['height']<90: continue
                            alt=img.get_attribute('alt') or ''
                            title=img.get_attribute('title') or ''
                            src=img.get_attribute('src') or img.get_attribute('data-src') or ''
                            text=' '.join([alt,title,src])
                            if bad_text(text,i): continue
                            key=(src or alt or title).strip()
                            if not key or key in seen: continue
                            # Reject obvious page chrome / logos by aspect and tiny source patterns.
                            if box['width']/max(box['height'],1)>4.5: continue
                            if any(x in src.lower() for x in ['logo','icon','favicon','sprite']): continue
                            fn=next_filename(i,rec)
                            img.screenshot(path=str(OUT/fn),type='png')
                            rec['screenshots'].append({
                                'file':fn,
                                'asset_type':'search_result_thumbnail_screenshot',
                                'search_query':q,
                                'search_result_title':alt or title,
                                'source_page':'https://www.bing.com/images/search?q='+quote_plus(q),
                                'original_image_url':src,
                                'captured_at_utc':datetime.now(timezone.utc).isoformat(),
                                'screenshot_mode':'visible_bing_image_element',
                                'counts_toward_39':True,
                                'usage_note':'Non-commercial screenshot fallback requested by user. Copyright/source terms still apply; no paywall/login/DRM/access-control bypass was used.',
                                'access_controls_bypassed':False
                            })
                            seen.add(key); added+=1
                        except Exception:
                            continue
                except Exception:
                    continue
        browser.close()
    total=0
    for rec in data.get('items',[]):
        c=existing_count(rec); rec['visual_asset_count']=c; rec['missing_visual_assets']=max(0,TARGET-c); total+=c
    data['version']='19.0-original-first-robust-counted-search-thumbnail-screenshot-fallback'
    data['screenshot_count']=sum(len(x.get('screenshots') or []) for x in data.get('items',[]))
    data['visual_asset_count']=total
    data['missing_visual_assets']=max(0,len(NEWS)*TARGET-total)
    data.setdefault('rules',{})['search_thumbnail_screenshot_fallback']=True
    data['rules']['screenshots_count_toward_target']=True
    data['rules']['no_bypass_of_paywall_login_drm_or_access_controls']=True
    MAN.write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
    readme=OUT/'README_来源与许可.txt'
    old=readme.read_text(encoding='utf-8') if readme.exists() else ''
    readme.write_text(old+'\nV19：若近期实拍原图不足，直接截取公开可见的 Bing 图片搜索结果中的图片元素补位，并计入三十九张目标；不绕过登录、付费墙、DRM或其他访问控制。\n',encoding='utf-8')
    stamp=datetime.now(ZoneInfo('Asia/Shanghai')).strftime('%Y-%m-%d')
    zp=ROOT/f'daily-news-images-{stamp}.zip'
    if zp.exists(): zp.unlink()
    with zipfile.ZipFile(zp,'w',zipfile.ZIP_DEFLATED) as z:
        for p in sorted(OUT.glob('??_?.jpg')): z.write(p,p.name)
        for p in sorted(OUT.glob('??_?.jpeg')): z.write(p,p.name)
        for p in sorted(OUT.glob('??_?.webp')): z.write(p,p.name)
        for p in sorted(OUT.glob('??_?.png')): z.write(p,p.name)
        z.writestr('manifest.json',MAN.read_text(encoding='utf-8'))
        z.writestr('README_来源与许可.txt',readme.read_text(encoding='utf-8'))
    print(f'V19 added screenshots={added}; total_visual_assets={total}/{len(NEWS)*TARGET}; zip={zp.name}')

if __name__=='__main__': main()
