from __future__ import annotations
import hashlib, html, io, json, os, re, shutil, time, zipfile
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlparse
from zoneinfo import ZoneInfo

import requests
from PIL import Image

ROOT=Path(__file__).resolve().parent
NEWS=json.loads((ROOT/'news.json').read_text(encoding='utf-8'))
POOL=json.loads((ROOT/'curated_pool.json').read_text(encoding='utf-8'))
OUT=ROOT/'output'; IMG=OUT/'images'
N=int(os.getenv('IMAGES_PER_NEWS','3')); MIN_W=int(os.getenv('MIN_WIDTH','1200')); MIN_H=int(os.getenv('MIN_HEIGHT','675'))
BING_LIMIT=int(os.getenv('BING_LIMIT','60')); OPENVERSE_LIMIT=int(os.getenv('OPENVERSE_LIMIT','60')); COMMONS_LIMIT=int(os.getenv('COMMONS_LIMIT','60'))
MIN_RECENT_YEAR=int(os.getenv('MIN_RECENT_YEAR','2025'))
COMMONS_API='https://commons.wikimedia.org/w/api.php'; OPENVERSE_API='https://api.openverse.org/v1/images/'; BING_IMAGES='https://www.bing.com/images/search'
S=requests.Session(); S.headers.update({'User-Agent':'Mozilla/5.0 Chrome/126 daily-news-image-pack/12.0','Accept-Language':'en-US,en;q=0.9'})

REJECT=('diagram','chart','graph','illustration','drawing','painting','poster','logo','icon','render','rendering','infographic','cartoon','collage','coat of arms','emblem','3d model','vector','locator map','route map','wallpaper','concept art','fan art','ai generated','generated by ai','midjourney','stable diffusion','dall-e','dalle','stock illustration')
STORY={
1:{'groups':[['hormuz','persian gulf','gulf of oman'],['ship','vessel','navy','tanker','strait']], 'avoid':['gibraltar','suez','panama']},
2:{'groups':[['kyiv','kiev'],['damage','destroy','attack','strike','building','city']], 'avoid':['moscow','odesa','odessa','kharkiv']},
3:{'groups':[['iran','iranian'],['radar','air base','airbase','military','missile','facility','installation']], 'avoid':['iraq','ain al-assad','museum']},
4:{'groups':[['hormuz','persian gulf','gulf of oman'],['merchant','cargo','tanker','ship','vessel']], 'avoid':['gibraltar','suez']},
5:{'groups':[['tanker','oil tanker','crude carrier'],['ship','vessel','sea','gulf','hormuz']], 'avoid':['motor oil','lubricant','engine oil','bottle']},
6:{'groups':[['qatar','qatarenergy','qatargas','persian gulf'],['lng','liquefied natural gas','gas carrier','carrier']], 'avoid':['sunset','resort','beach','tourism']},
7:{'groups':[['black sea','bosphorus','ukraine','turkey'],['cargo','merchant','ship','vessel','freighter']], 'avoid':['cruise','yacht']},
8:{'groups':[['data center','datacenter','server','computing'],['rack','server','data centre','computer']], 'avoid':['gaming','wallpaper','concept art']},
9:{'groups':[['china','chinese','xinjiang','khorgos'],['freight','container','intermodal','rail','train','logistics']], 'avoid':['great wall','flag','tourist']},
10:{'groups':[['china','shenzhen','xinjiang'],['transmission','power grid','substation','tower','high voltage','electricity']], 'avoid':['telecom tower','cell tower']},
11:{'groups':[['china','hong kong','construction'],['worker','helmet','hard hat','safety','protective']], 'avoid':['product only','shopping','isolated helmet']},
12:{'groups':[['xinjiang','turpan','urumqi','china'],['solar','photovoltaic','energy storage','power station','wind farm','renewable']], 'avoid':['foundation','trantor','sci-fi','wallpaper','concept art']},
13:{'groups':[['khorgos','horgos','xinjiang'],['port','border','freight','truck','train','terminal','customs']], 'avoid':['wedding','battery','hotel','restaurant']}
}

class BingParser(HTMLParser):
    def __init__(self): super().__init__(); self.items=[]
    def handle_starttag(self,tag,attrs):
        if tag!='a': return
        d=dict(attrs); m=d.get('m'); classes=d.get('class','')
        if 'iusc' not in classes or not m:return
        try:o=json.loads(html.unescape(m))
        except Exception:return
        u=o.get('murl') or o.get('turl'); p=o.get('purl') or ''; t=o.get('t') or o.get('desc') or ''
        if u:self.items.append({'download_url':u,'source_page':p,'title':t})

def clean(s): return re.sub(r'<[^>]+>',' ',s or '').replace('&nbsp;',' ').strip()
def blob(*x): return ' '.join(clean(v) for v in x if v).lower()
def reject(*x): return any(k in blob(*x) for k in REJECT)
def topic_ok(item_id,*parts):
    b=blob(*parts); p=STORY[int(item_id)]
    if any(a in b for a in p['avoid']): return False
    return all(any(term in b for term in g) for g in p['groups'])
def years_in(*parts): return [int(x) for x in re.findall(r'(?<!\d)(20(?:2[4-9]|3\d))(?!\d)',blob(*parts))]
def recent_year(*parts):
    ys=years_in(*parts); return max(ys) if ys else None

def verify(data):
    if not data:return None
    try:
        im=Image.open(io.BytesIO(data)); fmt=(im.format or '').upper(); w,h=im.size
        if fmt not in {'JPEG','PNG','WEBP'} or w<MIN_W or h<MIN_H:return None
        # animated/graphic-prone formats are rejected; photographs overwhelmingly arrive as raster JPEG/PNG/WEBP
        return w,h,fmt
    except Exception:return None

def get_bytes(url):
    try:
        r=S.get(url,timeout=30,allow_redirects=True,headers={'Referer':'https://www.bing.com/'}); r.raise_for_status()
        ct=(r.headers.get('content-type') or '').lower()
        if 'svg' in ct or 'text/html' in ct:return None
        return r.content if len(r.content)>20000 else None
    except Exception:return None

def key(c): return hashlib.sha1((c.get('download_url') or c.get('source_page') or c.get('title') or '').encode()).hexdigest()

def commons_search(q,item_id):
    try:
        r=S.get(COMMONS_API,params={'action':'query','format':'json','generator':'search','gsrsearch':q,'gsrnamespace':6,'gsrlimit':COMMONS_LIMIT,'prop':'imageinfo','iiprop':'url|size|mime|extmetadata','iiurlwidth':1800,'redirects':1},timeout=30);r.raise_for_status(); pages=list((r.json().get('query',{}).get('pages') or {}).values())
    except Exception:return []
    out=[]
    for p in pages:
        ii=(p.get('imageinfo') or [{}])[0]; e=ii.get('extmetadata') or {}; title=p.get('title',''); desc=clean(((e.get('ImageDescription') or {}).get('value',''))); cats=clean(((e.get('Categories') or {}).get('value','')))
        dt=clean(((e.get('DateTimeOriginal') or {}).get('value',''))) or clean(((e.get('DateTime') or {}).get('value','')))
        yr=recent_year(dt,title,desc)
        if reject(title,desc,cats) or not topic_ok(item_id,title,desc,cats) or not yr or yr<MIN_RECENT_YEAR:continue
        mime=(ii.get('mime') or '').lower(); ow=int(ii.get('width') or 0);oh=int(ii.get('height') or 0)
        if mime not in {'image/jpeg','image/png','image/webp'} or ow<MIN_W or oh<MIN_H:continue
        out.append({'title':title,'download_url':ii.get('thumburl') or ii.get('url',''),'source_page':ii.get('descriptionurl',''),'source':'Wikimedia Commons','license':clean(((e.get('LicenseShortName') or {}).get('value',''))),'license_url':((e.get('LicenseUrl') or {}).get('value','')),'captured_or_source_date':dt,'recent_year':yr,'recent_evidence':'Commons metadata date','source_tier':'commons-recent-photo'})
    return [x for x in out if x['download_url']]

def openverse_search(q,item_id):
    try:r=S.get(OPENVERSE_API,params={'q':q,'page_size':OPENVERSE_LIMIT,'mature':'false'},timeout=30);r.raise_for_status(); arr=r.json().get('results') or []
    except Exception:return []
    out=[]
    for x in arr:
        url=x.get('url') or x.get('thumbnail') or ''; title=x.get('title') or ''; page=x.get('foreign_landing_url') or ''; created=x.get('created_on') or ''
        yr=recent_year(created,title,page,url)
        if not url or reject(title,page,url) or not topic_ok(item_id,title,page,url) or not yr or yr<MIN_RECENT_YEAR:continue
        out.append({'title':title,'download_url':url,'source_page':page,'source':x.get('source') or 'Openverse','license':((x.get('license') or '')+' '+(x.get('license_version') or '')).strip(),'license_url':x.get('license_url') or '','creator':x.get('creator') or '','captured_or_source_date':created,'recent_year':yr,'recent_evidence':'Openverse created_on / URL-year evidence','source_tier':'openverse-recent-photo'})
    return out

def bing_search(q,item_id):
    try:
        # Explicitly bias search toward photographs from the two newest years.
        rq=f'{q} photograph 2026 OR 2025 -illustration -render -wallpaper -AI'; r=S.get(BING_IMAGES,params={'q':rq,'form':'HDRSC3','first':'1','qft':'+filterui:photo-photo'},timeout=30);r.raise_for_status();p=BingParser();p.feed(r.text)
    except Exception:return []
    out=[]
    for x in p.items[:BING_LIMIT]:
        yr=recent_year(x.get('title',''),x.get('source_page',''),x.get('download_url',''))
        if reject(x.get('title',''),x.get('source_page',''),x.get('download_url','')) or not topic_ok(item_id,x.get('title',''),x.get('source_page',''),x.get('download_url','')):continue
        # Bing cannot prove EXIF capture date. Accept only candidates carrying explicit 2025/2026 date evidence and label that evidence honestly.
        if not yr or yr<MIN_RECENT_YEAR:continue
        x.update({'source':'Bing Images full-web search','license':'unknown-check-source-page','license_url':'','recent_year':yr,'recent_evidence':'year visible in title/source/image URL; capture date not independently verified','source_tier':'bing-recent-photo-evidence'})
        out.append(x)
    return out

def exact_commons(title,item_id):
    # Exact curated filenames still pass topic and recency checks; no legacy photo is allowed just because it is curated.
    try:
        r=S.get(COMMONS_API,params={'action':'query','format':'json','titles':title,'prop':'imageinfo','iiprop':'url|size|mime|extmetadata','iiurlwidth':1800,'redirects':1},timeout=30);r.raise_for_status(); pages=list((r.json().get('query',{}).get('pages') or {}).values())
    except Exception:return []
    out=[]
    for p in pages:
        ii=(p.get('imageinfo') or [{}])[0];e=ii.get('extmetadata') or {};t=p.get('title',title);desc=clean(((e.get('ImageDescription') or {}).get('value','')));dt=clean(((e.get('DateTimeOriginal') or {}).get('value',''))) or clean(((e.get('DateTime') or {}).get('value','')));yr=recent_year(dt,t,desc)
        if not ii or reject(t,desc) or not topic_ok(item_id,t,desc) or not yr or yr<MIN_RECENT_YEAR:continue
        u=ii.get('thumburl') or ii.get('url') or ''
        if u:out.append({'title':t,'download_url':u,'source_page':ii.get('descriptionurl',''),'source':'Wikimedia Commons','license':clean(((e.get('LicenseShortName') or {}).get('value',''))),'license_url':((e.get('LicenseUrl') or {}).get('value','')),'captured_or_source_date':dt,'recent_year':yr,'recent_evidence':'Commons metadata date','source_tier':'curated-exact-recent'})
    return out

def ext(fmt):return {'JPEG':'.jpg','PNG':'.png','WEBP':'.webp'}.get(fmt,'.jpg')

def main():
    shutil.rmtree(OUT,ignore_errors=True);IMG.mkdir(parents=True,exist_ok=True)
    used=set();items=[];total=0;diagnostics={}
    for item in NEWS:
        pid=str(item['id']);pool=POOL.get(pid,{});rec={'id':item['id'],'title':item['title'],'images':[]};candidates=[];diag=[]
        for t in pool.get('files') or []:
            a=exact_commons(t,item['id']);candidates+=a;diag.append({'type':'exact-recent','query':t,'accepted':len(a)})
        queries=list(pool.get('queries') or []); queries += [item['title']] if item.get('title') else []
        # Add explicit recency variants instead of accepting old generic search results.
        expanded=[]
        for q in queries:
            expanded.extend([q+' 2026',q+' 2025'])
        for q in expanded:
            a=commons_search(q,item['id']);b=openverse_search(q,item['id']);c=bing_search(q,item['id']);candidates+=a+b+c
            diag.append({'query':q,'commons_recent':len(a),'openverse_recent':len(b),'bing_recent_evidence':len(c)});time.sleep(.08)
        uniq=[];seen=set()
        # verified capture/source metadata first; Bing evidence last
        candidates.sort(key=lambda c:(0 if c['source_tier'].startswith(('commons','curated')) else 1 if c['source_tier'].startswith('openverse') else 2, -(c.get('recent_year') or 0)))
        for c in candidates:
            k=key(c)
            if k in seen:continue
            seen.add(k);uniq.append(c)
        for c in uniq:
            if len(rec['images'])>=N:break
            k=key(c)
            if k in used:continue
            data=get_bytes(c['download_url']);ck=verify(data)
            if not ck:continue
            w,h,fmt=ck;fn=f"{int(item['id']):02d}_{len(rec['images'])+1}{ext(fmt)}";(IMG/fn).write_bytes(data);m=dict(c);m.update({'file':fn,'width':w,'height':h,'format':fmt,'real_photo_filter_passed':True});rec['images'].append(m);used.add(k);total+=1
        rec['missing']=N-len(rec['images']);items.append(rec);diagnostics[pid]=diag;print(f"{int(item['id']):02d}: {len(rec['images'])}/{N} recent_relevant_candidates={len(uniq)}")
    manifest={'generated_at_utc':datetime.now(timezone.utc).isoformat(),'generated_at_beijing':datetime.now(ZoneInfo('Asia/Shanghai')).isoformat(),'version':'12.0-full-web-recent-real-photo','downloaded_images':total,'missing_images':13*N-total,'items':items,'diagnostics':diagnostics,'rules':{'search_scope':'full web','engines':['Wikimedia Commons','Openverse','Bing Images'],'real_photo_only':True,'reject_ai_render_illustration':True,'story_specific_relevance_groups':True,'minimum_recent_year':MIN_RECENT_YEAR,'commons_requires_metadata_date':True,'openverse_requires_recent_date_evidence':True,'bing_requires_explicit_recent_year_evidence':True,'bing_capture_date_not_claimed_verified':True,'target_images':13*N,'minimum':[MIN_W,MIN_H]}}
    (OUT/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
    lines=['每日新闻相关图片包 v12 · 全网实拍/近期优先','',f'实际下载：{total}/{13*N} 张。',f'硬性近期门槛：仅接收具有 {MIN_RECENT_YEAR} 年或之后日期证据的图片。','Commons 优先要求元数据日期；Openverse 要求日期证据；Bing 仅在标题/来源/图片URL明确带近期年份时接受，并在 manifest 明确标注其拍摄日期未独立核验。','所有候选必须通过每条新闻独立的主题关键词组，并排除 AI、渲染、插画、壁纸、图表等。','']+[f"{r['id']:02d}. {r['title']} — {len(r['images'])}/{N}" for r in items]
    (OUT/'README_来源与许可.txt').write_text('\n'.join(lines),encoding='utf-8')
    stamp=datetime.now(ZoneInfo('Asia/Shanghai')).strftime('%Y-%m-%d');zp=ROOT/f'daily-news-images-{stamp}.zip'
    if zp.exists():zp.unlink()
    with zipfile.ZipFile(zp,'w',zipfile.ZIP_DEFLATED) as z:
        for p in sorted(IMG.iterdir()):z.write(p,p.name)
        z.write(OUT/'manifest.json','manifest.json');z.write(OUT/'README_来源与许可.txt','README_来源与许可.txt')
    print(f'Downloaded {total}/{13*N}; ZIP={zp.name}')
if __name__=='__main__':main()
