from __future__ import annotations
import hashlib,html,io,json,os,re,shutil,time,zipfile
from datetime import datetime,timezone
from html.parser import HTMLParser
from pathlib import Path
from zoneinfo import ZoneInfo
import requests
from PIL import Image

ROOT=Path(__file__).resolve().parent
NEWS=json.loads((ROOT/'news.json').read_text(encoding='utf-8'))
POOL=json.loads((ROOT/'curated_pool.json').read_text(encoding='utf-8'))
OUT=ROOT/'output'; IMG=OUT/'images'
N=int(os.getenv('IMAGES_PER_NEWS','3')); MIN_W=int(os.getenv('MIN_WIDTH','1200')); MIN_H=int(os.getenv('MIN_HEIGHT','675')); MIN_YEAR=int(os.getenv('MIN_RECENT_YEAR','2025'))
COMMONS_LIMIT=int(os.getenv('COMMONS_LIMIT','80')); BING_LIMIT=int(os.getenv('BING_LIMIT','80'))
COMMONS='https://commons.wikimedia.org/w/api.php'; BING='https://www.bing.com/images/search'
S=requests.Session();S.headers.update({'User-Agent':'Mozilla/5.0 Chrome/126 daily-news-image-pack/14.0','Accept-Language':'en-US,en;q=0.9'})
REJECT=('illustration','drawing','painting','poster','logo','icon','render','rendering','infographic','cartoon','collage','3d','vector','wallpaper','concept art','fan art','ai generated','generated by ai','midjourney','stable diffusion','dall-e','dalle','diagram','chart','graph','map')
STORY={1:(['hormuz','persian gulf','gulf of oman'],['ship','vessel','navy','tanker']),2:(['kyiv','kiev'],['damage','destroy','attack','strike','building','city']),3:(['iran','iranian'],['radar','air base','airbase','military','missile','facility','installation']),4:(['hormuz','persian gulf','gulf of oman'],['merchant','cargo','tanker','ship','vessel']),5:(['tanker','oil tanker','crude carrier'],['ship','vessel','gulf','hormuz','sea']),6:(['qatar','qatarenergy','qatargas','persian gulf'],['lng','liquefied natural gas','gas carrier','carrier']),7:(['black sea','bosphorus','ukraine','turkey'],['cargo','merchant','ship','vessel','freighter']),8:(['data center','datacenter','server'],['rack','server','data centre']),9:(['china','chinese','xinjiang','khorgos'],['freight','container','intermodal','rail','train','logistics']),10:(['china','shenzhen','xinjiang'],['transmission','power grid','substation','tower','high voltage','electricity']),11:(['china','hong kong','construction'],['worker','helmet','hard hat','safety','protective']),12:(['xinjiang','turpan','urumqi','china'],['solar','photovoltaic','energy storage','power station','wind farm','renewable']),13:(['khorgos','horgos','xinjiang'],['port','border','freight','truck','train','terminal','customs'])}
AVOID={1:['gibraltar','suez','panama'],2:['moscow','odesa','odessa','kharkiv'],3:['iraq','ain al-assad','museum'],4:['gibraltar','suez'],5:['motor oil','lubricant','engine oil','bottle'],6:['sunset','resort','beach','tourism'],7:['cruise','yacht'],8:['gaming'],9:['great wall','flag','tourist'],10:['telecom tower','cell tower'],11:['shopping','isolated helmet'],12:['foundation','trantor','sci-fi'],13:['wedding','battery','hotel','restaurant']}

class BP(HTMLParser):
 def __init__(self):super().__init__();self.items=[]
 def handle_starttag(self,tag,attrs):
  if tag!='a':return
  d=dict(attrs);m=d.get('m')
  if 'iusc' not in d.get('class','') or not m:return
  try:o=json.loads(html.unescape(m))
  except:return
  u=o.get('murl') or o.get('turl');p=o.get('purl') or '';t=o.get('t') or o.get('desc') or ''
  if u:self.items.append({'download_url':u,'source_page':p,'title':t})

def clean(s):return re.sub(r'<[^>]+>',' ',s or '').replace('&nbsp;',' ').strip()
def txt(*x):return ' '.join(clean(v) for v in x if v).lower()
def years(*x):return [int(y) for y in re.findall(r'(?<!\d)(202[5-9]|203\d)(?!\d)',txt(*x))]
def reject(*x):return any(k in txt(*x) for k in REJECT)
def topic_ok(i,*parts):
 b=txt(*parts)
 if reject(b) or any(a in b for a in AVOID[i]):return False
 g1,g2=STORY[i];return any(a in b for a in g1) and any(a in b for a in g2)
def verify(data):
 if not data:return None
 try:
  im=Image.open(io.BytesIO(data));fmt=(im.format or '').upper();w,h=im.size
  if fmt not in {'JPEG','PNG','WEBP'} or w<MIN_W or h<MIN_H:return None
  ex=im.getexif();dt=str(ex.get(36867,'') or ex.get(306,'') or '') if ex else '';ys=years(dt);ey=max(ys) if ys else None
  return w,h,fmt,ey,dt
 except:return None
def get(url):
 try:
  r=S.get(url,timeout=30,allow_redirects=True,headers={'Referer':'https://www.bing.com/'});r.raise_for_status();ct=(r.headers.get('content-type') or '').lower()
  if 'svg' in ct or 'text/html' in ct:return None
  return r.content if len(r.content)>20000 else None
 except:return None

def commons_pages(params):
 try:
  r=S.get(COMMONS,params=params,timeout=30);r.raise_for_status();return list((r.json().get('query',{}).get('pages') or {}).values())
 except:return []
def cmeta(p,curated=False,i=None):
 ii=(p.get('imageinfo') or [{}])[0];e=ii.get('extmetadata') or {};title=p.get('title','');desc=clean(((e.get('ImageDescription') or {}).get('value','')));cats=clean(((e.get('Categories') or {}).get('value','')));dt=clean(((e.get('DateTimeOriginal') or {}).get('value',''))) or clean(((e.get('DateTime') or {}).get('value','')));ys=years(dt,title,desc);yr=max(ys) if ys else None
 if not ii or reject(title,desc,cats) or not yr or yr<MIN_YEAR:return None
 if not curated and i and not topic_ok(i,title,desc,cats):return None
 mime=(ii.get('mime') or '').lower();ow=int(ii.get('width') or 0);oh=int(ii.get('height') or 0)
 if mime not in {'image/jpeg','image/png','image/webp'} or ow<MIN_W or oh<MIN_H:return None
 u=ii.get('thumburl') or ii.get('url') or ''
 if not u:return None
 return {'title':title,'download_url':u,'source_page':ii.get('descriptionurl',''),'source':'Wikimedia Commons','source_tier':'curated-exact-recent' if curated else 'commons-recent-search','recent_year':yr,'recent_evidence':'Commons DateTimeOriginal/DateTime/title metadata','captured_or_source_date':dt,'license':clean(((e.get('LicenseShortName') or {}).get('value',''))),'license_url':((e.get('LicenseUrl') or {}).get('value','')),'recency_confidence':'high' if 'DateTimeOriginal' in e else 'medium-high'}
def exact_commons(title,i):
 ps=commons_pages({'action':'query','format':'json','titles':title,'prop':'imageinfo','iiprop':'url|size|mime|extmetadata','iiurlwidth':1800,'redirects':1})
 return [c for p in ps if (c:=cmeta(p,curated=True,i=i))]
def commons_search(q,i):
 ps=commons_pages({'action':'query','format':'json','generator':'search','gsrsearch':q,'gsrnamespace':6,'gsrlimit':COMMONS_LIMIT,'prop':'imageinfo','iiprop':'url|size|mime|extmetadata','iiurlwidth':1800,'redirects':1})
 return [c for p in ps if (c:=cmeta(p,curated=False,i=i))]
def page_date(url):
 if not url:return None,''
 try:r=S.get(url,timeout=15,allow_redirects=True);r.raise_for_status();h=r.text[:700000]
 except:return None,''
 pats=[r'(?:datePublished|article:published_time|dateCreated|uploadDate|dateModified)["\'\s:=]+(?:content=)?["\']?([^"\'<>]{4,50})',r'(?<!\d)(202[5-9]|203\d)[-/.](0?[1-9]|1[0-2])[-/.]([0-3]?\d)']
 for p in pats:
  m=re.search(p,h,re.I)
  if m:
   ys=years(m.group(0));
   if ys:return max(ys),m.group(0)[:160]
 return None,''
def bing_search(q,i):
 try:
  rq=f'{q} 2026 OR 2025 photo photograph -illustration -render -wallpaper -AI';r=S.get(BING,params={'q':rq,'qft':'+filterui:photo-photo','form':'HDRSC3'},timeout=25);r.raise_for_status();p=BP();p.feed(r.text)
 except:return []
 out=[]
 for x in p.items[:BING_LIMIT]:
  if not topic_ok(i,x['title'],x['source_page'],x['download_url']):continue
  ys=years(x['title'],x['source_page'],x['download_url']);yr=max(ys) if ys else None;ev='search-result title/source/image URL year' if yr else ''
  if not yr:
   yr,pe=page_date(x['source_page']);ev='source page recent publication/upload evidence: '+pe if yr else ''
  if not yr or yr<MIN_YEAR:continue
  x.update({'source':'Bing Images full-web search','source_tier':'bing-recent-web-photo','recent_year':yr,'recent_evidence':ev,'license':'unknown-check-source-page','recency_confidence':'medium'});out.append(x)
 return out
def key(c):return hashlib.sha1((c.get('download_url','')+c.get('source_page','')).encode()).hexdigest()
def ext(f):return {'JPEG':'.jpg','PNG':'.png','WEBP':'.webp'}.get(f,'.jpg')

def main():
 shutil.rmtree(OUT,ignore_errors=True);IMG.mkdir(parents=True,exist_ok=True);used=set();items=[];total=0;diagnostics={}
 for item in NEWS:
  i=int(item['id']);pool=POOL.get(str(i),{});rec={'id':i,'title':item['title'],'images':[]};cand=[];di=[]
  for t in pool.get('files') or []:
   a=exact_commons(t,i);cand+=a;di.append({'type':'curated-exact','query':t,'accepted':len(a)})
  qs=list(pool.get('queries') or []);qs += [item['title']] if item.get('title') else []
  for q in qs:
   a=commons_search(q+' 2026',i)+commons_search(q+' 2025',i);b=bing_search(q,i);cand+=a+b;di.append({'query':q,'commons_recent':len(a),'bing_recent':len(b)});time.sleep(.08)
  uniq=[];seen=set()
  cand.sort(key=lambda c:(0 if c['source'].startswith('Wikimedia') else 1,-(c.get('recent_year') or 0)))
  for c in cand:
   z=key(c)
   if z not in seen:seen.add(z);uniq.append(c)
  for c in uniq:
   if len(rec['images'])>=N:break
   z=key(c)
   if z in used:continue
   data=get(c['download_url']);ck=verify(data)
   if not ck:continue
   w,h,fmt,ey,edt=ck
   if ey and ey<MIN_YEAR:continue
   fn=f'{i:02d}_{len(rec["images"])+1}{ext(fmt)}';(IMG/fn).write_bytes(data);m=dict(c);m.update({'file':fn,'width':w,'height':h,'format':fmt,'exif_year':ey,'exif_datetime':edt,'real_photo_filter_passed':True,'capture_date_verified':bool(ey and ey>=MIN_YEAR)});rec['images'].append(m);used.add(z);total+=1
  rec['missing']=N-len(rec['images']);items.append(rec);diagnostics[str(i)]=di;print(f'{i:02d}: {len(rec["images"])}/{N} candidates={len(uniq)}')
 manifest={'generated_at_utc':datetime.now(timezone.utc).isoformat(),'generated_at_beijing':datetime.now(ZoneInfo('Asia/Shanghai')).isoformat(),'version':'14.0-hybrid-recent-real-photo','downloaded_images':total,'missing_images':13*N-total,'items':items,'diagnostics':diagnostics,'rules':{'search_scope':'full web + curated Commons','real_photo_only':True,'reject_ai_render_illustration':True,'story_specific_relevance':True,'minimum_recent_year':MIN_YEAR,'curated_exact_requires_recent_metadata':True,'web_requires_recent_source_evidence':True,'capture_date_verified_only_when_exif_or_explicit_photo_metadata':True,'target_images':13*N,'minimum':[MIN_W,MIN_H]}}
 (OUT/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8');(OUT/'README_来源与许可.txt').write_text(f'每日新闻相关图片包 v14\n实际下载：{total}/{13*N} 张。\n只保留真实照片候选，拒绝AI/插画/渲染；优先Commons中有2025/2026明确图片元数据的实拍图，其次使用全网页面有近期证据的实拍候选。\nmanifest中的 capture_date_verified=true 仅表示图片EXIF或明确图片元数据验证到2025年及以后；普通网页发布日期不会冒充拍摄日期。\n',encoding='utf-8')
 stamp=datetime.now(ZoneInfo('Asia/Shanghai')).strftime('%Y-%m-%d');zp=ROOT/f'daily-news-images-{stamp}.zip';
 if zp.exists():zp.unlink()
 with zipfile.ZipFile(zp,'w',zipfile.ZIP_DEFLATED) as z:
  for p in sorted(IMG.iterdir()):z.write(p,p.name)
  z.write(OUT/'manifest.json','manifest.json');z.write(OUT/'README_来源与许可.txt','README_来源与许可.txt')
 print(f'Downloaded {total}/{13*N}; ZIP={zp.name}')
if __name__=='__main__':main()
