from __future__ import annotations
import hashlib,html,io,json,os,re,shutil,time,zipfile
from datetime import datetime,timezone
from html.parser import HTMLParser
from pathlib import Path
from zoneinfo import ZoneInfo
import requests
from PIL import Image

ROOT=Path(__file__).resolve().parent
NEWS=json.loads((ROOT/'news.json').read_text(encoding='utf-8'))
POOL=json.loads((ROOT/'curated_pool.json').read_text(encoding='utf-8'))
OUT=ROOT/'output'; IMG=OUT/'images'
N=int(os.getenv('IMAGES_PER_NEWS','3')); MIN_W=int(os.getenv('MIN_WIDTH','1200')); MIN_H=int(os.getenv('MIN_HEIGHT','675')); MIN_YEAR=int(os.getenv('MIN_RECENT_YEAR','2025'))
COMMONS_LIMIT=int(os.getenv('COMMONS_LIMIT','100')); BING_LIMIT=int(os.getenv('BING_LIMIT','100'))
COMMONS='https://commons.wikimedia.org/w/api.php'; BING='https://www.bing.com/images/search'
S=requests.Session();S.headers.update({'User-Agent':'Mozilla/5.0 Chrome/126 daily-news-image-pack/15.0','Accept-Language':'en-US,en;q=0.9'})
REJECT=('illustration','drawing','painting','poster','logo','icon','render','rendering','infographic','cartoon','collage','3d','vector','wallpaper','concept art','fan art','ai generated','generated by ai','midjourney','stable diffusion','dall-e','dalle','diagram','chart','graph','map')
STORY={1:(['hormuz','persian gulf','gulf of oman'],['ship','vessel','navy','tanker']),2:(['kyiv','kiev'],['damage','destroy','attack','strike','building','city']),3:(['iran','iranian'],['radar','air base','airbase','military','missile','facility','installation']),4:(['hormuz','persian gulf','gulf of oman'],['merchant','cargo','tanker','ship','vessel']),5:(['tanker','oil tanker','crude carrier'],['ship','vessel','gulf','hormuz','sea']),6:(['qatar','qatarenergy','qatargas','persian gulf'],['lng','liquefied natural gas','gas carrier','carrier']),7:(['black sea','bosphorus','ukraine','turkey'],['cargo','merchant','ship','vessel','freighter']),8:(['data center','datacenter','server'],['rack','server','data centre']),9:(['china','chinese','xinjiang','khorgos'],['freight','container','intermodal','rail','train','logistics']),10:(['china','shenzhen','xinjiang'],['transmission','power grid','substation','tower','high voltage','electricity']),11:(['china','hong kong','construction'],['worker','helmet','hard hat','safety','protective']),12:(['xinjiang','turpan','urumqi','china'],['solar','photovoltaic','energy storage','power station','wind farm','renewable']),13:(['khorgos','horgos','xinjiang'],['port','border','freight','truck','train','terminal','customs'])}
AVOID={1:['gibraltar','suez','panama'],2:['moscow','odesa','odessa','kharkiv'],3:['iraq','ain al-assad','museum'],4:['gibraltar','suez'],5:['motor oil','lubricant','engine oil','bottle'],6:['sunset','resort','beach','tourism'],7:['cruise','yacht'],8:['gaming'],9:['great wall','flag','tourist'],10:['telecom tower','cell tower'],11:['shopping','isolated helmet'],12:['foundation','trantor','sci-fi'],13:['wedding','battery','hotel','restaurant']}

class BP(HTMLParser):
 def __init__(self):super().__init__();self.items=[]
 def handle_starttag(self,tag,attrs):
  if tag!='a':return
  d=dict(attrs);m=d.get('m')
  if 'iusc' not in d.get('class','') or not m:return
  try:o=json.loads(html.unescape(m))
  except:return
  u=o.get('murl') or o.get('turl');p=o.get('purl') or '';t=o.get('t') or o.get('desc') or ''
  if u:self.items.append({'download_url':u,'source_page':p,'title':t})

def clean(s):return re.sub(r'<[^>]+>',' ',s or '').replace('&nbsp;',' ').strip()
def txt(*x):return ' '.join(clean(v) for v in x if v).lower()
def reject(*x):return any(k in txt(*x) for k in REJECT)
def topic_ok(i,*parts):
 b=txt(*parts)
 if reject(b) or any(a in b for a in AVOID[i]):return False
 g1,g2=STORY[i];return any(a in b for a in g1) and any(a in b for a in g2)
def year_from_text(*parts):
 ys=[int(y) for y in re.findall(r'(?<!\d)(202[5-9]|203\d)(?!\d)',txt(*parts))]
 return max(ys) if ys else None

def explicit_capture_date_text(*parts):
 b=' '.join(clean(v) for v in parts if v)
 pats=[
  r'(?<!\d)(202[5-9]|203\d)[-/.](0?[1-9]|1[0-2])[-/.]([0-3]?\d)(?!\d)',
  r'(?<!\d)([0-3]?\d)\s+(January|February|March|April|May|June|July|August|September|October|November|December)\s+(202[5-9]|203\d)(?!\d)',
  r'(January|February|March|April|May|June|July|August|September|October|November|December)\s+([0-3]?\d),?\s+(202[5-9]|203\d)(?!\d)'
 ]
 for p in pats:
  m=re.search(p,b,re.I)
  if m:
   y=year_from_text(m.group(0))
   if y and y>=MIN_YEAR:return y,m.group(0)
 return None,''

def verify(data):
 if not data:return None
 try:
  im=Image.open(io.BytesIO(data));fmt=(im.format or '').upper();w,h=im.size
  if fmt not in {'JPEG','PNG','WEBP'} or w<MIN_W or h<MIN_H:return None
  ex=im.getexif();dt=str(ex.get(36867,'') or ex.get(306,'') or '') if ex else '';ey=year_from_text(dt)
  return w,h,fmt,ey,dt
 except:return None

def get(url,referer='https://www.bing.com/'):
 try:
  r=S.get(url,timeout=30,allow_redirects=True,headers={'Referer':referer});r.raise_for_status();ct=(r.headers.get('content-type') or '').lower()
  if 'svg' in ct or 'text/html' in ct:return None
  return r.content if len(r.content)>20000 else None
 except:return None

def commons_pages(params):
 try:
  r=S.get(COMMONS,params=params,timeout=30);r.raise_for_status();return list((r.json().get('query',{}).get('pages') or {}).values())
 except:return []
def cmeta(p,curated=False,i=None):
 ii=(p.get('imageinfo') or [{}])[0];e=ii.get('extmetadata') or {};title=p.get('title','');desc=clean(((e.get('ImageDescription') or {}).get('value','')));cats=clean(((e.get('Categories') or {}).get('value','')))
 if not ii or reject(title,desc,cats):return None
 if not curated and i and not topic_ok(i,title,desc,cats):return None
 orig=clean(((e.get('DateTimeOriginal') or {}).get('value','')))
 # Only DateTimeOriginal is treated as a verified photo capture date. DateTime/upload date is not enough.
 yr=year_from_text(orig); ev='Commons DateTimeOriginal'
 if not yr:
  yr,cap=explicit_capture_date_text(title,desc); ev='explicit date in Commons photo title/description: '+cap if yr else ''
 if not yr or yr<MIN_YEAR:return None
 mime=(ii.get('mime') or '').lower();ow=int(ii.get('width') or 0);oh=int(ii.get('height') or 0)
 if mime not in {'image/jpeg','image/png','image/webp'} or ow<MIN_W or oh<MIN_H:return None
 u=ii.get('thumburl') or ii.get('url') or ''
 if not u:return None
 return {'title':title,'download_url':u,'source_page':ii.get('descriptionurl',''),'source':'Wikimedia Commons','source_tier':'curated-exact-verified-capture' if curated else 'commons-verified-capture','recent_year':yr,'recent_evidence':ev,'captured_or_source_date':orig,'license':clean(((e.get('LicenseShortName') or {}).get('value',''))),'license_url':((e.get('LicenseUrl') or {}).get('value','')),'capture_date_verified':True,'recency_confidence':'high'}
def exact_commons(title,i):
 ps=commons_pages({'action':'query','format':'json','titles':title,'prop':'imageinfo','iiprop':'url|size|mime|extmetadata','iiurlwidth':1800,'redirects':1})
 return [c for p in ps if (c:=cmeta(p,curated=True,i=i))]
def commons_search(q,i):
 ps=commons_pages({'action':'query','format':'json','generator':'search','gsrsearch':q,'gsrnamespace':6,'gsrlimit':COMMONS_LIMIT,'prop':'imageinfo','iiprop':'url|size|mime|extmetadata','iiurlwidth':1800,'redirects':1})
 return [c for p in ps if (c:=cmeta(p,curated=False,i=i))]

def source_page_capture_date(url):
 if not url:return None,'',''
 try:r=S.get(url,timeout=18,allow_redirects=True);r.raise_for_status();h=r.text[:900000]
 except:return None,'',''
 # Require language linking a date to a photo/image/caption, not merely article publication date.
 pats=[
  r'(?:photo(?:graph)?|image|pictured|taken|shot|captured)[^<>]{0,180}(202[5-9]|203\d)[-/.](0?[1-9]|1[0-2])[-/.]([0-3]?\d)',
  r'(202[5-9]|203\d)[-/.](0?[1-9]|1[0-2])[-/.]([0-3]?\d)[^<>]{0,180}(?:photo(?:graph)?|image|pictured|taken|shot|captured)',
  r'(?:photo(?:graph)?|image|pictured|taken|shot|captured)[^<>]{0,180}(January|February|March|April|May|June|July|August|September|October|November|December)\s+([0-3]?\d),?\s+(202[5-9]|203\d)'
 ]
 for p in pats:
  m=re.search(p,h,re.I)
  if m:
   y=year_from_text(m.group(0))
   if y and y>=MIN_YEAR:return y,m.group(0)[:220],clean(re.sub(r'<[^>]+>',' ',m.group(0)))
 return None,'',''

def bing_search(q,i):
 try:
  rq=f'{q} 2026 2025 photo photograph -illustration -render -wallpaper -AI';r=S.get(BING,params={'q':rq,'qft':'+filterui:photo-photo','form':'HDRSC3'},timeout=25);r.raise_for_status();p=BP();p.feed(r.text)
 except:return []
 out=[]
 for x in p.items[:BING_LIMIT]:
  if not topic_ok(i,x['title'],x['source_page'],x['download_url']):continue
  # Search-result years alone no longer count. The source page must explicitly tie a recent date to the photo/image.
  yr,ev,caption=source_page_capture_date(x['source_page'])
  if not yr:continue
  x.update({'source':'Bing Images full-web search','source_tier':'bing-verified-photo-caption-date','recent_year':yr,'recent_evidence':'source-page photo/caption date: '+ev,'verified_caption':caption,'license':'unknown-check-source-page','capture_date_verified':True,'recency_confidence':'high'});out.append(x)
 return out

def key(c):return hashlib.sha1((c.get('download_url','')+c.get('source_page','')).encode()).hexdigest()
def ext(f):return {'JPEG':'.jpg','PNG':'.png','WEBP':'.webp'}.get(f,'.jpg')

def main():
 shutil.rmtree(OUT,ignore_errors=True);IMG.mkdir(parents=True,exist_ok=True);used=set();items=[];total=0;diagnostics={}
 for item in NEWS:
  i=int(item['id']);pool=POOL.get(str(i),{});rec={'id':i,'title':item['title'],'images':[]};cand=[];di=[]
  for t in pool.get('files') or []:
   a=exact_commons(t,i);cand+=a;di.append({'type':'curated-exact-verified','query':t,'accepted':len(a)})
  qs=list(pool.get('queries') or []);qs += [item['title']] if item.get('title') else []
  expanded=[]
  for q in qs:expanded += [q+' 2026',q+' 2025']
  for q in expanded:
   a=commons_search(q,i);b=bing_search(q,i);cand+=a+b;di.append({'query':q,'commons_verified':len(a),'bing_verified_caption_date':len(b)});time.sleep(.06)
  uniq=[];seen=set();cand.sort(key=lambda c:(0 if c['source'].startswith('Wikimedia') else 1,-(c.get('recent_year') or 0)))
  for c in cand:
   z=key(c)
   if z not in seen:seen.add(z);uniq.append(c)
  for c in uniq:
   if len(rec['images'])>=N:break
   z=key(c)
   if z in used:continue
   data=get(c['download_url'],c.get('source_page') or 'https://www.bing.com/');ck=verify(data)
   if not ck:continue
   w,h,fmt,ey,edt=ck
   if ey and ey<MIN_YEAR:continue
   fn=f'{i:02d}_{len(rec["images"])+1}{ext(fmt)}';(IMG/fn).write_bytes(data)
   m=dict(c);m.update({'file':fn,'width':w,'height':h,'format':fmt,'exif_year':ey,'exif_datetime':edt,'real_photo_filter_passed':True});rec['images'].append(m);used.add(z);total+=1
  rec['missing']=N-len(rec['images']);items.append(rec);diagnostics[str(i)]=di;print(f'{i:02d}: {len(rec["images"])}/{N} verified_recent_capture_candidates={len(uniq)}')
 manifest={'generated_at_utc':datetime.now(timezone.utc).isoformat(),'generated_at_beijing':datetime.now(ZoneInfo('Asia/Shanghai')).isoformat(),'version':'15.0-verified-recent-capture-only','downloaded_images':total,'missing_images':13*N-total,'items':items,'diagnostics':diagnostics,'rules':{'search_scope':'full web + Wikimedia Commons','real_photo_only':True,'reject_ai_render_illustration':True,'story_specific_relevance':True,'minimum_recent_year':MIN_YEAR,'capture_date_must_be_verified':True,'accepted_capture_evidence':['EXIF DateTimeOriginal >=2025','Commons DateTimeOriginal >=2025','explicit date in Commons photo title/description >=2025','source-page caption/text explicitly linking photo/image/taken/captured to date >=2025'],'article_publication_date_alone_not_accepted':True,'search_result_year_alone_not_accepted':True,'target_images':13*N,'minimum':[MIN_W,MIN_H]}}
 (OUT/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
 (OUT/'README_来源与许可.txt').write_text(f'每日新闻相关图片包 v15 · 近期拍摄日期核验版\n实际下载：{total}/{13*N} 张。\nZIP只收录真实照片，并且必须存在可核验的2025年及以后拍摄日期证据。\n文章发布日期、搜索结果年份本身不再作为“最近拍摄”的证明。宁可缺图，也不以旧照或无法核实拍摄日期的图片凑数。\n',encoding='utf-8')
 stamp=datetime.now(ZoneInfo('Asia/Shanghai')).strftime('%Y-%m-%d');zp=ROOT/f'daily-news-images-{stamp}.zip'
 if zp.exists():zp.unlink()
 with zipfile.ZipFile(zp,'w',zipfile.ZIP_DEFLATED) as z:
  for p in sorted(IMG.iterdir()):z.write(p,p.name)
  z.write(OUT/'manifest.json','manifest.json');z.write(OUT/'README_来源与许可.txt','README_来源与许可.txt')
 print(f'Downloaded {total}/{13*N}; ZIP={zp.name}')
if __name__=='__main__':main()
